# Generated by Django 4.0.5 on 2022-06-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Date_of_Birth',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Email_Address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_super_teacher',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='users',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='users',
            name='perfil',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
